server {
    listen      80;
    server_name .financedev.xyz;

    modsecurity off;

    # security
    include     nginxconfig.io/security.conf;

    # logging
    access_log  /var/log/nginx/financedev.xyz.access.log cloudflare buffer=512k flush=1m;
    error_log   /var/log/nginx/financedev.xyz.error.log warn;

    # reverse proxy
    location / {
        proxy_pass            http://172.31.0.6;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}
