Include /etc/nginx/modsec/modsecurity.conf
Include /etc/nginx/modsec/coreruleset-4.24.1/crs-setup.conf
Include /etc/nginx/modsec/custom/*.conf
Include /etc/nginx/modsec/coreruleset-4.24.1/rules/*.conf
